--------------------------------------------------------
--  Fichier créé - lundi-décembre-06-2021   
--------------------------------------------------------
DROP TABLE "DHIA"."CALENDRIER";
DROP TABLE "DHIA"."CERTIFICAT";
DROP TABLE "DHIA"."COURS";
DROP TABLE "DHIA"."EXAMEN";
DROP TABLE "DHIA"."FORMATION";
--------------------------------------------------------
--  DDL for Table CALENDRIER
--------------------------------------------------------

  CREATE TABLE "DHIA"."CALENDRIER" 
   (	"IDE" NUMBER, 
	"DATE_EXAM" DATE, 
	"TEMPS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CERTIFICAT
--------------------------------------------------------

  CREATE TABLE "DHIA"."CERTIFICAT" 
   (	"IDCERTIF" NUMBER(*,0), 
	"CATEGORIE" VARCHAR2(255 BYTE), 
	"CIBLE" VARCHAR2(255 BYTE), 
	"TITRE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COURS
--------------------------------------------------------

  CREATE TABLE "DHIA"."COURS" 
   (	"IDC" NUMBER, 
	"MATIERE" VARCHAR2(255 BYTE), 
	"TEMPS" VARCHAR2(255 BYTE), 
	"DUREE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXAMEN
--------------------------------------------------------

  CREATE TABLE "DHIA"."EXAMEN" 
   (	"IDE" NUMBER(*,0), 
	"MATIERE" VARCHAR2(255 BYTE), 
	"DUREE" VARCHAR2(255 BYTE), 
	"NOTE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMATION
--------------------------------------------------------

  CREATE TABLE "DHIA"."FORMATION" 
   (	"IDF" NUMBER(*,0), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PERIODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DHIA.CALENDRIER
SET DEFINE OFF;
Insert into DHIA.CALENDRIER (IDE,DATE_EXAM,TEMPS) values ('1',to_date('01/01/00','DD/MM/RR'),'60min');
REM INSERTING into DHIA.CERTIFICAT
SET DEFINE OFF;
REM INSERTING into DHIA.COURS
SET DEFINE OFF;
REM INSERTING into DHIA.EXAMEN
SET DEFINE OFF;
REM INSERTING into DHIA.FORMATION
SET DEFINE OFF;
Insert into DHIA.FORMATION (IDF,TYPE,PERIODE) values ('0',null,null);
Insert into DHIA.FORMATION (IDF,TYPE,PERIODE) values ('89','7','7');
Insert into DHIA.FORMATION (IDF,TYPE,PERIODE) values ('7894','12','54');
Insert into DHIA.FORMATION (IDF,TYPE,PERIODE) values ('9875','065','999');
Insert into DHIA.FORMATION (IDF,TYPE,PERIODE) values ('7','456','478');
Insert into DHIA.FORMATION (IDF,TYPE,PERIODE) values ('10','456','478');
Insert into DHIA.FORMATION (IDF,TYPE,PERIODE) values ('789','456','478');
Insert into DHIA.FORMATION (IDF,TYPE,PERIODE) values ('1','456','478');
--------------------------------------------------------
--  DDL for Index CALENDRIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."CALENDRIER_PK" ON "DHIA"."CALENDRIER" ("IDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CERTIFICAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."CERTIFICAT_PK" ON "DHIA"."CERTIFICAT" ("IDCERTIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."COURS_PK" ON "DHIA"."COURS" ("IDC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EXAMEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."EXAMEN_PK" ON "DHIA"."EXAMEN" ("IDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."FORMATION_PK" ON "DHIA"."FORMATION" ("IDF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALENDRIER
--------------------------------------------------------

  ALTER TABLE "DHIA"."CALENDRIER" ADD CONSTRAINT "CALENDRIER_PK" PRIMARY KEY ("IDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."CALENDRIER" MODIFY ("IDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CERTIFICAT
--------------------------------------------------------

  ALTER TABLE "DHIA"."CERTIFICAT" ADD CONSTRAINT "CERTIFICAT_PK" PRIMARY KEY ("IDCERTIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."CERTIFICAT" MODIFY ("IDCERTIF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURS
--------------------------------------------------------

  ALTER TABLE "DHIA"."COURS" ADD CONSTRAINT "COURS_PK" PRIMARY KEY ("IDC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."COURS" MODIFY ("IDC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXAMEN
--------------------------------------------------------

  ALTER TABLE "DHIA"."EXAMEN" ADD CONSTRAINT "EXAMEN_PK" PRIMARY KEY ("IDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."EXAMEN" MODIFY ("IDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORMATION
--------------------------------------------------------

  ALTER TABLE "DHIA"."FORMATION" ADD CONSTRAINT "FORMATION_PK" PRIMARY KEY ("IDF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."FORMATION" MODIFY ("IDF" NOT NULL ENABLE);
