--------------------------------------------------------
--  File created - Tuesday-November-02-2021   
--------------------------------------------------------
DROP TABLE "SYSTEM"."ANNONCE_CIBLES" cascade constraints;
DROP TABLE "SYSTEM"."ANNONCE_MAIL_DATE" cascade constraints;
DROP TABLE "SYSTEM"."ANNONCES" cascade constraints;
DROP TABLE "SYSTEM"."CANDIDATS" cascade constraints;
DROP TABLE "SYSTEM"."CONCERNER" cascade constraints;
DROP TABLE "SYSTEM"."EDITER" cascade constraints;
DROP TABLE "SYSTEM"."EMPLOYERS" cascade constraints;
DROP TABLE "SYSTEM"."FACTURES" cascade constraints;
DROP TABLE "SYSTEM"."FICHE_PAIE" cascade constraints;
DROP TABLE "SYSTEM"."FORMATION" cascade constraints;
DROP TABLE "SYSTEM"."GESTION_CANDIDAT_FORMATION" cascade constraints;
DROP TABLE "SYSTEM"."GESTION_EMPLOYER_ANNONCES" cascade constraints;
DROP TABLE "SYSTEM"."GESTION_PARTENAIRES_EMPLOYERS" cascade constraints;
DROP TABLE "SYSTEM"."PARTENAIRES" cascade constraints;
--------------------------------------------------------
--  DDL for Table ANNONCE_CIBLES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ANNONCE_CIBLES" 
   (	"ID_CIBLE" NUMBER, 
	"ID_ANNONCE" NUMBER, 
	"CIBLE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANNONCE_MAIL_DATE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ANNONCE_MAIL_DATE" 
   (	"DATE_MAIL" DATE, 
	"ID_ANNONCE" NUMBER, 
	"ID_DATE_MAIL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANNONCES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ANNONCES" 
   (	"ID_ANNONCE" NUMBER, 
	"DUREE" NUMBER(*,0), 
	"DATE_CREATION" DATE DEFAULT sysdate, 
	"DESIGN" BLOB, 
	"PRIX_TOTAL" NUMBER DEFAULT 0, 
	"FACILITE" NUMBER(*,0) DEFAULT 0, 
	"NBR_MOIS" NUMBER(*,0) DEFAULT 1, 
	"AVANCE" NUMBER DEFAULT 0, 
	"INTERET" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESIGN") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CANDIDATS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CANDIDATS" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONCERNER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONCERNER" 
   (	"ID_PARTENAIRE" NUMBER, 
	"ID_FACTURE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EDITER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EDITER" 
   (	"ID_EMPLOYER" NUMBER, 
	"NUM_FICHE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYERS" 
   (	"ID_EMP" NUMBER, 
	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE_NAISSANCE" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"DEPARTEMENT" VARCHAR2(20 BYTE), 
	"TELEPHONE" NUMBER, 
	"SALAIRE_BASE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FACTURES" 
   (	"ID_FACTURE" NUMBER, 
	"TTC" NUMBER, 
	"TVA" NUMBER, 
	"MONTANT_PAYE" NUMBER, 
	"REMISE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FICHE_PAIE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FICHE_PAIE" 
   (	"NUMFICHE" NUMBER, 
	"SALAIRE_BRUT" NUMBER, 
	"SALAIRE_NET" NUMBER, 
	"RETENU_FISCAL" NUMBER, 
	"DATE_PAIE" DATE, 
	"RETENUE_CNSS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FORMATION" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"PERIODE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_CANDIDAT_FORMATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_CANDIDAT_FORMATION" 
   (	"CIN" NUMBER, 
	"ID_FORAMTION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_EMPLOYER_ANNONCES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_EMPLOYER_ANNONCES" 
   (	"ID_ANNONCE" NUMBER, 
	"ID_EMP" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_PARTENAIRES_EMPLOYERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_PARTENAIRES_EMPLOYERS" 
   (	"ID_PARTENAIRE" NUMBER, 
	"ID_EMPLOYER" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTENAIRES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PARTENAIRES" 
   (	"ID_PARTENAIRE" NUMBER, 
	"ADRESSE" VARCHAR2(30 BYTE), 
	"NUMERO" NUMBER, 
	"ADRESSE_MAIL" VARCHAR2(30 BYTE), 
	"NOM" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ANNONCE_CIBLES
SET DEFINE OFF;
REM INSERTING into SYSTEM.ANNONCE_MAIL_DATE
SET DEFINE OFF;
REM INSERTING into SYSTEM.ANNONCES
SET DEFINE OFF;
REM INSERTING into SYSTEM.CANDIDATS
SET DEFINE OFF;
REM INSERTING into SYSTEM.CONCERNER
SET DEFINE OFF;
REM INSERTING into SYSTEM.EDITER
SET DEFINE OFF;
REM INSERTING into SYSTEM.EMPLOYERS
SET DEFINE OFF;
REM INSERTING into SYSTEM.FACTURES
SET DEFINE OFF;
REM INSERTING into SYSTEM.FICHE_PAIE
SET DEFINE OFF;
REM INSERTING into SYSTEM.FORMATION
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_CANDIDAT_FORMATION
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_EMPLOYER_ANNONCES
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_PARTENAIRES_EMPLOYERS
SET DEFINE OFF;
REM INSERTING into SYSTEM.PARTENAIRES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ANNONCE_CIBLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ANNONCE_CIBLES_PK" ON "SYSTEM"."ANNONCE_CIBLES" ("ID_CIBLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANNONCE_MAIL_DATE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ANNONCE_MAIL_DATE_PK1" ON "SYSTEM"."ANNONCE_MAIL_DATE" ("ID_DATE_MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANNONCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ANNONCES_PK" ON "SYSTEM"."ANNONCES" ("ID_ANNONCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TABLE1_PK" ON "SYSTEM"."CANDIDATS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONCERNER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CONCERNER_PK" ON "SYSTEM"."CONCERNER" ("ID_PARTENAIRE", "ID_FACTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EDITER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EDITER_PK" ON "SYSTEM"."EDITER" ("ID_EMPLOYER", "NUM_FICHE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYERS_PK" ON "SYSTEM"."EMPLOYERS" ("ID_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FACTURES_PK" ON "SYSTEM"."FACTURES" ("ID_FACTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FICHE_PAIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FICHE_PAIE_PK" ON "SYSTEM"."FICHE_PAIE" ("NUMFICHE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FORMATION_PK" ON "SYSTEM"."FORMATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GESTION_CANDIDAT_FORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_CANDIDAT_FORMATION_PK" ON "SYSTEM"."GESTION_CANDIDAT_FORMATION" ("CIN", "ID_FORAMTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GESTION_EMPLOYER_ANNONCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_EMPLOYER_ANNONCES_PK" ON "SYSTEM"."GESTION_EMPLOYER_ANNONCES" ("ID_EMP", "ID_ANNONCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GESTION_PARTENAIRES_EMPLOY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_PARTENAIRES_EMPLOY_PK" ON "SYSTEM"."GESTION_PARTENAIRES_EMPLOYERS" ("ID_PARTENAIRE", "ID_EMPLOYER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTENAIRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PARTENAIRES_PK" ON "SYSTEM"."PARTENAIRES" ("ID_PARTENAIRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANNONCE_CIBLES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANNONCE_CIBLES" ADD CONSTRAINT "ANNONCE_CIBLES_PK" PRIMARY KEY ("ID_CIBLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ANNONCE_CIBLES" MODIFY ("ID_ANNONCE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCE_CIBLES" MODIFY ("ID_CIBLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANNONCE_MAIL_DATE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANNONCE_MAIL_DATE" ADD CONSTRAINT "ANNONCE_MAIL_DATE_PK" PRIMARY KEY ("ID_DATE_MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ANNONCE_MAIL_DATE" MODIFY ("ID_DATE_MAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCE_MAIL_DATE" MODIFY ("ID_ANNONCE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCE_MAIL_DATE" MODIFY ("DATE_MAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANNONCES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANNONCES" MODIFY ("INTERET" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCES" MODIFY ("NBR_MOIS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCES" MODIFY ("FACILITE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCES" MODIFY ("PRIX_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCES" MODIFY ("DATE_CREATION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCES" MODIFY ("DUREE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANNONCES" ADD CONSTRAINT "ANNONCES_PK" PRIMARY KEY ("ID_ANNONCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ANNONCES" MODIFY ("ID_ANNONCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANDIDATS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CANDIDATS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CANDIDATS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONCERNER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONCERNER" ADD CONSTRAINT "CONCERNER_PK" PRIMARY KEY ("ID_PARTENAIRE", "ID_FACTURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CONCERNER" MODIFY ("ID_FACTURE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONCERNER" MODIFY ("ID_PARTENAIRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDITER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EDITER" ADD CONSTRAINT "EDITER_PK" PRIMARY KEY ("ID_EMPLOYER", "NUM_FICHE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EDITER" MODIFY ("ID_EMPLOYER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EDITER" MODIFY ("NUM_FICHE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYERS" ADD CONSTRAINT "EMPLOYERS_PK" PRIMARY KEY ("ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EMPLOYERS" MODIFY ("ID_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FACTURES" ADD CONSTRAINT "FACTURES_PK" PRIMARY KEY ("ID_FACTURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FACTURES" MODIFY ("MONTANT_PAYE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FACTURES" MODIFY ("TVA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FACTURES" MODIFY ("TTC" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FACTURES" MODIFY ("ID_FACTURE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FICHE_PAIE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FICHE_PAIE" ADD CONSTRAINT "FICHE_PAIE_PK" PRIMARY KEY ("NUMFICHE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FICHE_PAIE" MODIFY ("RETENUE_CNSS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FICHE_PAIE" MODIFY ("DATE_PAIE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FICHE_PAIE" MODIFY ("RETENU_FISCAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FICHE_PAIE" MODIFY ("SALAIRE_NET" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FICHE_PAIE" MODIFY ("SALAIRE_BRUT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FICHE_PAIE" MODIFY ("NUMFICHE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORMATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FORMATION" ADD CONSTRAINT "FORMATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FORMATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GESTION_CANDIDAT_FORMATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_CANDIDAT_FORMATION" ADD CONSTRAINT "GESTION_CANDIDAT_FORMATION_PK" PRIMARY KEY ("CIN", "ID_FORAMTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_CANDIDAT_FORMATION" MODIFY ("ID_FORAMTION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_CANDIDAT_FORMATION" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GESTION_EMPLOYER_ANNONCES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER_ANNONCES" ADD CONSTRAINT "GESTION_EMPLOYER_ANNONCES_PK" PRIMARY KEY ("ID_EMP", "ID_ANNONCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER_ANNONCES" MODIFY ("ID_EMP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER_ANNONCES" MODIFY ("ID_ANNONCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GESTION_PARTENAIRES_EMPLOYERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_PARTENAIRES_EMPLOYERS" ADD CONSTRAINT "GESTION_PARTENAIRES_EMPLOY_PK" PRIMARY KEY ("ID_PARTENAIRE", "ID_EMPLOYER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_PARTENAIRES_EMPLOYERS" MODIFY ("ID_EMPLOYER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_PARTENAIRES_EMPLOYERS" MODIFY ("ID_PARTENAIRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTENAIRES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PARTENAIRES" ADD CONSTRAINT "PARTENAIRES_PK" PRIMARY KEY ("ID_PARTENAIRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PARTENAIRES" MODIFY ("ID_PARTENAIRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANNONCE_CIBLES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANNONCE_CIBLES" ADD CONSTRAINT "AC_ANNONCE" FOREIGN KEY ("ID_ANNONCE")
	  REFERENCES "SYSTEM"."ANNONCES" ("ID_ANNONCE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANNONCE_MAIL_DATE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANNONCE_MAIL_DATE" ADD CONSTRAINT "AMD_ANNONCE_FK" FOREIGN KEY ("ID_ANNONCE")
	  REFERENCES "SYSTEM"."ANNONCES" ("ID_ANNONCE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONCERNER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONCERNER" ADD CONSTRAINT "CONCERNER_FACTURE_FK" FOREIGN KEY ("ID_FACTURE")
	  REFERENCES "SYSTEM"."FACTURES" ("ID_FACTURE") ENABLE;
  ALTER TABLE "SYSTEM"."CONCERNER" ADD CONSTRAINT "CONCERNER_PARTENAIRE_FK" FOREIGN KEY ("ID_PARTENAIRE")
	  REFERENCES "SYSTEM"."PARTENAIRES" ("ID_PARTENAIRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EDITER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EDITER" ADD CONSTRAINT "EDITER_EMPLOYER_FK" FOREIGN KEY ("ID_EMPLOYER")
	  REFERENCES "SYSTEM"."EMPLOYERS" ("ID_EMP") ENABLE;
  ALTER TABLE "SYSTEM"."EDITER" ADD CONSTRAINT "EDITER_FICHE_FK" FOREIGN KEY ("NUM_FICHE")
	  REFERENCES "SYSTEM"."FICHE_PAIE" ("NUMFICHE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GESTION_CANDIDAT_FORMATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_CANDIDAT_FORMATION" ADD CONSTRAINT "GCF_CANDIDAT_FK" FOREIGN KEY ("CIN")
	  REFERENCES "SYSTEM"."CANDIDATS" ("CIN") ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_CANDIDAT_FORMATION" ADD CONSTRAINT "GCF_FORMATION_FK" FOREIGN KEY ("ID_FORAMTION")
	  REFERENCES "SYSTEM"."FORMATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GESTION_EMPLOYER_ANNONCES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER_ANNONCES" ADD CONSTRAINT "GEA_ANNONCES_FK" FOREIGN KEY ("ID_ANNONCE")
	  REFERENCES "SYSTEM"."ANNONCES" ("ID_ANNONCE") ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER_ANNONCES" ADD CONSTRAINT "GEA_EMPLOYER_FK" FOREIGN KEY ("ID_EMP")
	  REFERENCES "SYSTEM"."EMPLOYERS" ("ID_EMP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GESTION_PARTENAIRES_EMPLOYERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_PARTENAIRES_EMPLOYERS" ADD CONSTRAINT "GPE_EMPLOYERS" FOREIGN KEY ("ID_EMPLOYER")
	  REFERENCES "SYSTEM"."EMPLOYERS" ("ID_EMP") ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_PARTENAIRES_EMPLOYERS" ADD CONSTRAINT "GPE_PARTENAIRES_FK" FOREIGN KEY ("ID_PARTENAIRE")
	  REFERENCES "SYSTEM"."PARTENAIRES" ("ID_PARTENAIRE") ENABLE;
