INSERT INTO ANNONCES 
(DUREE, DATE_CREATION, CIBLE, ID_EMPLOYER)
VALUES
(2, TO_DATE('17/12/2015', 'DD/MM/YYYY'), 'tous', 13);

INSERT INTO CANDIDATS
(CIN,ADRESSE_MAIL,COMPETANCE)
VALUES
(1,'armen.bakir@esprit.tn','Digital Marketing');

INSERT INTO CANDIDATS
(CIN,ADRESSE_MAIL,COMPETANCE)
VALUES
(2,'eya.harbi@esprit.tn','Graphic Design');


INSERT INTO CANDIDATS
(CIN,ADRESSE_MAIL,COMPETANCE)
VALUES
(3,'armen.bakir@esprit.tn','Graphic Design');

UPDATE ANNONCES
SET EMAIL_ENVOYEE = 1
WHERE ID_ANNONCE = 25;
